# Default values for riojadotnet-gitops-example-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: borjareinares/riojadotnet-gitops-example
  pullPolicy: IfNotPresent
  tag: "0.1"

service:
  type: ClusterIP
  port: 5000
